name: Python Tests
on:
  push:
    branches:
      - "*"
jobs:
  pytest:
    container:
      image: docker.repo.frg.tech/python:3.13
    runs-on:
      - self-hosted
    steps:
      - name: Checkout repo
        uses: fancom-developer/gh-checkout-action@v1
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Setup python
        run: uv python install
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Run tests
        run: uv run coverage run -m pytest
      - name: Run linter
        run: uv run ruff check .
