name: Run Python Tests, Typechecks, and Linters

on: [push]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Setup python
        run: uv python install
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Run tests
        run: uv run coverage run -m pytest
      - name: Run typechecks
        run: uv run mypy .
      - name: Run linter
        run: uv run ruff check .
      - name: Run doc linter
        run: >
          uv run pydoclint
          --style=google
          --arg-type-hints-in-docstring=False
          --check-return-types=False
          --allow-init-docstring=True
          ./src
